config/routes.rb
Rails.application.routes.draw do
  get 'hotzak/index'

  get 'pizza/index'

  get 'deserts/index'

  get 'naps/index'

  get 'exels/index'

  get 'salats/index'

  get 'coldrolls/index'

  get 'sushis/index'

  get 'dopkrolls/index'

  get 'asss/index'

  get 'clasrolls/index'

  get 'firmrolls/index'

  get 'zaprolls/index'

  get 'hotrolls/index'

  get 'admin' => 'admin#index'
  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  get 'sessions/create'

  get 'sessions/destroy'

  resources :users

  resources :orders

  resources :line_items

  resources :carts

  get 'store/index'

  resources :products do
    get :who_bought, on: :member
  end

  resources :products

  root to: 'hotrolls#index', as: 'hotrolls'
end

app/models/cart.rb
# -*- encoding : utf-8 -*-
class Cart < ActiveRecord::Base
	has_many :line_items, dependent: :destroy

	def add_product(product_id)
		current_item = line_items.find_by(product_id: product_id) 
		if current_item
			current_item.quantily += 1
		else
			current_item = line_items.build(product_id: product_id)
		end
		current_item
	end

	def total_price
		line_items.to_a.sum { |item| item.total_price }
	end
end

app/models/line_item.rb
# -*- encoding : utf-8 -*-
class LineItem < ActiveRecord::Base
	belongs_to :order
  belongs_to :product
  belongs_to :cart

def total_price
	product.price * quantily
end

end

app/models/order.rb
# -*- encoding : utf-8 -*-
class Order < ActiveRecord::Base
	has_many :line_items, dependent: :destroy
	validates :name, :number, presence: true

	def add_line_items_from_cart(cart)
		cart.line_items.each do |item|
			item.cart_id = nil
			line_items << item
		end
	end
end

app/models/product.rb
# -*- encoding : utf-8 -*-
class Product < ActiveRecord::Base

	PRODUCT_TYPE = [ "Hot roll", "Zap roll", "Firm roll", 
		"Clas roll", "Ass", "Dop k roll",
		"Sushi", "Cold roll", "Salat", "Excl", "Nap", "Desert", "Pizza", "Hot Zakus" ]




	has_many :line_items
	has_many :order, through: :line_items

	validates :title, :image_url, :categor, presence: true
	validates :price, numericality: {greater_than_or_equal_to: 0.01}
	validates :title, uniqueness: true
	validates :image_url, allow_blank: true, format: {
		with: %r{\.(gif|jpg|png|jpeg)\Z}i,
		message: 'URL должен указывать на картинки'
	}

	def self.latest
		Product.order(:update_at).last
	end

	private

	def ensure_not_referenced_by_any_line_item
		if line_items.empty?
			return true
		else
			errors.add(:base, 'существуют товарные позиции')
			return false
		end
	end

end

app/models/user.rb
# -*- encoding : utf-8 -*-
class User < ActiveRecord::Base
	validates :name, presence: true, uniqueness: true
  	has_secure_password
  	after_destroy :ensure_an_admin_remains

  private
  	def ensure_an_admin_remains
  		if User.count.zero?
  			raise "Последний пользователь не может быть удален"
  		end
  	end
end

app/controllers/carts_controller.rb
# -*- encoding : utf-8 -*-
class CartsController < ApplicationController
  skip_before_action :authorize, only: [:create, :update, :destroy]
  before_action :set_cart, only: [:show, :edit, :update, :destroy]

  rescue_from ActiveRecord::RecordNotFound, with: :invalid_cart

  # GET /carts
  # GET /carts.json
  def index
    @carts = Cart.all
  end

  # GET /carts/1
  # GET /carts/1.json
  def show
  end

  # GET /carts/new
  def new
    @cart = Cart.new
  end

  # GET /carts/1/edit
  def edit
  end

  # POST /carts
  # POST /carts.json
  def create
    @cart = Cart.new(cart_params)

    respond_to do |format|
      if @cart.save
        format.html { redirect_to @cart }
        format.json { render :show, status: :created, location: @cart }
      else
        format.html { render :new }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /carts/1
  # PATCH/PUT /carts/1.json
  def update
    respond_to do |format|
      if @cart.update(cart_params)
        format.html { redirect_to @cart, notice: 'Cart was successfully updated.' }
        format.json { render :show, status: :ok, location: @cart }
      else
        format.html { render :edit }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /carts/1
  # DELETE /carts/1.json
  def destroy
    @cart.destroy if @cart.id == session[:cart_id]
    session[:cart_id] = nil
    respond_to do |format|
      format.html { redirect_to hotrolls_url}
      format.js {}
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cart
      @cart = Cart.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cart_params
      params[:cart]
    end

    def invalid_cart
    logger.error "Неверный id корзины. #{params[:id]}"
    redirect_to store_url, notice: 'Неверный id корзины. Хватит хацкать сайт!'
  end
end

app/helpers/admin_helper.rb
# -*- encoding : utf-8 -*-
module AdminHelper
end

app/helpers/asss_helper.rb
# -*- encoding : utf-8 -*-
module AsssHelper
end

app/helpers/carts_helper.rb
# -*- encoding : utf-8 -*-
module CartsHelper
end

app/helpers/deserts_helper.rb
# -*- encoding : utf-8 -*-
module DesertsHelper
end

app/helpers/exels_helper.rb
# -*- encoding : utf-8 -*-
module ExelsHelper
end

app/helpers/hotrolls_helper.rb
# -*- encoding : utf-8 -*-
module HotrollsHelper
end

app/helpers/hotzak_helper.rb
module HotzakHelper
end

app/helpers/naps_helper.rb
# -*- encoding : utf-8 -*-
module NapsHelper
end

app/helpers/orders_helper.rb
# -*- encoding : utf-8 -*-
module OrdersHelper
end

app/helpers/pizza_helper.rb
module PizzaHelper
end

app/helpers/products_helper.rb
# -*- encoding : utf-8 -*-
module ProductsHelper
end

app/helpers/salats_helper.rb
# -*- encoding : utf-8 -*-
module SalatsHelper
end

app/helpers/sessions_helper.rb
# -*- encoding : utf-8 -*-
module SessionsHelper
end

app/helpers/store_helper.rb
# -*- encoding : utf-8 -*-
module StoreHelper
end

app/helpers/sushis_helper.rb
# -*- encoding : utf-8 -*-
module SushisHelper
end

app/helpers/users_helper.rb
# -*- encoding : utf-8 -*-
module UsersHelper
end

app/helpers/zaprolls_helper.rb
# -*- encoding : utf-8 -*-
module ZaprollsHelper
end

app/views/carts/_cart.html.erb
<h2>Корзина</h2>
<table>
	<%= render(cart.line_items) %>
	<tr class="total_line">
		<td colspan="2">Итого</td>
		<td class="total_cell"><%= cart.total_price %> руб.</td>
	</tr>
</table>
<%= button_to 'Оформить', new_order_path, method: :get %>
<%= button_to 'Очистить Корзину', cart, method: :delete %>

app/views/carts/_form.html.erb
<%= form_for(@cart) do |f| %>
  <% if @cart.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cart.errors.count, "error") %> prohibited this cart from being saved:</h2>

      <ul>
      <% @cart.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name, size: 40 %>
  </div>

  <div class="field">
    <%= f.label :number %><br>
    <%= f.text_field :number, size: 40 %>
  </div>

  <div class="actions">
    <%= f.submit 'Оформить' %>
  </div>
<% end %>

app/views/carts/destroy.js.erb
if ($('#cart').length == 1) { $('#cart').hide("blind", {direction: "vertical" }, 1000); }

$('#cart tr').not('.total_line').remove();

app/views/carts/edit.html.erb
<h1>Editing cart</h1>

<%= render 'form' %>

<%= link_to 'Показать', @cart %> |
<%= link_to 'Назад', carts_path %>

app/views/carts/index.html.erb
<h1>Listing carts</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @carts.each do |cart| %>
      <tr>
        <td><%= link_to 'Show', cart %></td>
        <td><%= link_to 'Edit', edit_cart_path(cart) %></td>
        <td><%= link_to 'Destroy', cart, method: :delete, data: { confirm: 'Вы уверены?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Новая корзина', new_cart_path %>

app/views/carts/new.html.erb
<h1>Новый заказ</h1>

<div class="depot_form">
	<fieldset>
		<legend>Укажите детали для оформления заказа</legend>
		<%= render 'form'%>
	</fieldset>
</div>


<%= link_to 'Назад', carts_path %>

app/views/carts/show.html.erb
<% if notice %>
<p id="notice"><%= notice %></p>
<% end %>

<%= render @cart %>