config/routes.rb
Rails.application.routes.draw do
  get 'hotzak/index'

  get 'pizza/index'

  get 'deserts/index'

  get 'naps/index'

  get 'exels/index'

  get 'salats/index'

  get 'coldrolls/index'

  get 'sushis/index'

  get 'dopkrolls/index'

  get 'asss/index'

  get 'clasrolls/index'

  get 'firmrolls/index'

  get 'zaprolls/index'

  get 'hotrolls/index'

  get 'admin' => 'admin#index'
  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  get 'sessions/create'

  get 'sessions/destroy'

  resources :users

  resources :orders

  resources :line_items

  resources :carts

  get 'store/index'

  resources :products do
    get :who_bought, on: :member
  end

  resources :products

  root to: 'hotrolls#index', as: 'hotrolls'
end

app/models/cart.rb
# -*- encoding : utf-8 -*-
class Cart < ActiveRecord::Base
	has_many :line_items, dependent: :destroy

	def add_product(product_id)
		current_item = line_items.find_by(product_id: product_id) 
		if current_item
			current_item.quantily += 1
		else
			current_item = line_items.build(product_id: product_id)
		end
		current_item
	end

	def total_price
		line_items.to_a.sum { |item| item.total_price }
	end
end

app/models/line_item.rb
# -*- encoding : utf-8 -*-
class LineItem < ActiveRecord::Base
	belongs_to :order
  belongs_to :product
  belongs_to :cart

def total_price
	product.price * quantily
end

end

app/models/order.rb
# -*- encoding : utf-8 -*-
class Order < ActiveRecord::Base
	has_many :line_items, dependent: :destroy
	validates :name, :number, presence: true

	def add_line_items_from_cart(cart)
		cart.line_items.each do |item|
			item.cart_id = nil
			line_items << item
		end
	end
end

app/models/product.rb
# -*- encoding : utf-8 -*-
class Product < ActiveRecord::Base

	PRODUCT_TYPE = [ "Hot roll", "Zap roll", "Firm roll", 
		"Clas roll", "Ass", "Dop k roll",
		"Sushi", "Cold roll", "Salat", "Excl", "Nap", "Desert", "Pizza", "Hot Zakus" ]




	has_many :line_items
	has_many :order, through: :line_items

	validates :title, :image_url, :categor, presence: true
	validates :price, numericality: {greater_than_or_equal_to: 0.01}
	validates :title, uniqueness: true
	validates :image_url, allow_blank: true, format: {
		with: %r{\.(gif|jpg|png|jpeg)\Z}i,
		message: 'URL должен указывать на картинки'
	}

	def self.latest
		Product.order(:update_at).last
	end

	private

	def ensure_not_referenced_by_any_line_item
		if line_items.empty?
			return true
		else
			errors.add(:base, 'существуют товарные позиции')
			return false
		end
	end

end

app/models/user.rb
# -*- encoding : utf-8 -*-
class User < ActiveRecord::Base
	validates :name, presence: true, uniqueness: true
  	has_secure_password
  	after_destroy :ensure_an_admin_remains

  private
  	def ensure_an_admin_remains
  		if User.count.zero?
  			raise "Последний пользователь не может быть удален"
  		end
  	end
end

app/controllers/line_items_controller.rb
# -*- encoding : utf-8 -*-
class LineItemsController < ApplicationController
   skip_before_action :authorize, only: :create
  include CurrentCart
  before_action :set_cart, only: [:create]
  before_action :set_line_item, only: [:show, :edit, :update, :destroy]

  # GET /line_items
  # GET /line_items.json
  def index
    @line_items = LineItem.all
  end

  # GET /line_items/1
  # GET /line_items/1.json
  def show
  end

  # GET /line_items/new
  def new
    @line_item = LineItem.new
  end

  # GET /line_items/1/edit
  def edit
  end

  # POST /line_items
  # POST /line_items.json
  def create
    product = Product.find(params[:product_id]) 
    @line_item = @cart.add_product(product.id)

    respond_to do |format|
      if @line_item.save
        format.html { redirect_to store_url}
        format.js { @current_item = @line_item }
        format.json { render :show, status: :created, location: @line_item }
      else
        format.html { render :new }
        format.json { render json: @line_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /line_items/1
  # PATCH/PUT /line_items/1.json
  def update
    respond_to do |format|
      if @line_item.update(line_item_params)
        format.html { redirect_to @line_item}
        format.json { render :show, status: :ok, location: @line_item }
      else
        format.html { render :edit }
        format.json { render json: @line_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /line_items/1
  # DELETE /line_items/1.json
  def destroy
    @line_item.destroy
    respond_to do |format|
      format.html { redirect_to line_items_url}
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_line_item
      @line_item = LineItem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def line_item_params
      params.require(:line_item).permit(:product_id)
    end
end

app/helpers/admin_helper.rb
# -*- encoding : utf-8 -*-
module AdminHelper
end

app/helpers/asss_helper.rb
# -*- encoding : utf-8 -*-
module AsssHelper
end

app/helpers/carts_helper.rb
# -*- encoding : utf-8 -*-
module CartsHelper
end

app/helpers/deserts_helper.rb
# -*- encoding : utf-8 -*-
module DesertsHelper
end

app/helpers/exels_helper.rb
# -*- encoding : utf-8 -*-
module ExelsHelper
end

app/helpers/hotrolls_helper.rb
# -*- encoding : utf-8 -*-
module HotrollsHelper
end

app/helpers/hotzak_helper.rb
module HotzakHelper
end

app/helpers/line_items_helper.rb
# -*- encoding : utf-8 -*-
module LineItemsHelper
end

app/helpers/naps_helper.rb
# -*- encoding : utf-8 -*-
module NapsHelper
end

app/helpers/orders_helper.rb
# -*- encoding : utf-8 -*-
module OrdersHelper
end

app/helpers/pizza_helper.rb
module PizzaHelper
end

app/helpers/products_helper.rb
# -*- encoding : utf-8 -*-
module ProductsHelper
end

app/helpers/salats_helper.rb
# -*- encoding : utf-8 -*-
module SalatsHelper
end

app/helpers/sessions_helper.rb
# -*- encoding : utf-8 -*-
module SessionsHelper
end

app/helpers/store_helper.rb
# -*- encoding : utf-8 -*-
module StoreHelper
end

app/helpers/sushis_helper.rb
# -*- encoding : utf-8 -*-
module SushisHelper
end

app/helpers/users_helper.rb
# -*- encoding : utf-8 -*-
module UsersHelper
end

app/views/line_items/_form.html.erb
<%= form_for(@line_item) do |f| %>
  <% if @line_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@line_item.errors.count, "error") %> prohibited this line_item from being saved:</h2>

      <ul>
      <% @line_item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :product_id %><br>
    <%= f.text_field :product_id %>
  </div>
  <div class="field">
    <%= f.label :cart_id %><br>
    <%= f.text_field :cart_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/line_items/_line_item.html.erb
<% if line_item == @current_item %>
<tr id="current_item">
<% else %>
<tr>
<% end %>
	<td><%= line_item.quantily %>&times</td>
	<td><%= line_item.product.title %></td>
	<td class="item_price"><%= line_item.total_price %> руб.</td>
</tr>

app/views/line_items/_line_item.text.erb
<%= sprintf("%2d x %s",
	line_item.quantily,
	truncate(line_item.product.title, length: 50)) %>

app/views/line_items/create.js.erb
$('notice').hide();

if ($('#cart tr').length == 1) { $('#cart').show('blind', 500); }

$('#cart').html("<%= escape_javascript render(@cart) %>");

$('#current_item').css({'background-color':'#D4D8D1'}).animate({'background-color':'#332C2F'}, 1000);

app/views/line_items/edit.html.erb
<h1>Editing line_item</h1>

<%= render 'form' %>

<%= link_to 'Показать', @line_item %> |
<%= link_to 'Назад', line_items_path %>

app/views/line_items/index.html.erb
<h1>Listing line_items</h1>

<table>
  <thead>
    <tr>
      <th>Product</th>
      <th>Cart</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @line_items.each do |line_item| %>
      <tr>
        <td><%= line_item.product %></td>
        <td><%= line_item.cart %></td>
        <td><%= link_to 'Показать', line_item %></td>
        <td><%= link_to 'Изменить', edit_line_item_path(line_item) %></td>
        <td><%= link_to 'Удалить', line_item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Line item', new_line_item_path %>

app/views/line_items/new.html.erb
<h1>New line_item</h1>

<%= render 'form' %>

<%= link_to 'Назад', line_items_path %>

app/views/line_items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Product:</strong>
  <%= @line_item.product %>
</p>

<p>
  <strong>Cart:</strong>
  <%= @line_item.cart %>
</p>

<%= link_to 'Изменить', edit_line_item_path(@line_item) %> |
<%= link_to 'Назад', line_items_path %>